CREATE TABLE ingestion_config (
  ingestion_object_id  BIGINT GENERATED ALWAYS AS IDENTITY, 
  source_system_id     BIGINT NOT NULL,          
  source_schema        STRING NOT NULL,                   
  source_object_name   STRING NOT NULL,         
  source_object_type   STRING NOT NULL,          
  custom_query         STRING,                   
  source_filter        STRING,                   
  load_type            STRING NOT NULL,          
  write_mode           STRING NOT NULL,          
  incremental_column          STRING,                                     
  incremental_end_value       STRING,         
  primary_key_cols     STRING,           
  partition_column     STRING,
  data_read_size       BIGINT, 
  file_format          STRING,                   
  sheet_name           STRING,
  target_catalog       STRING NOT NULL,
  target_schema        STRING NOT NULL,
  target_table         STRING NOT NULL,
  schema_evolution_mode     STRING,                 
  pipeline_id         STRING,
  created_timestamp TIMESTAMP, 
  updated_timestamp TIMESTAMP, 
  last_updated_by STRING,
  created_by STRING,
  is_enabled BOOLEAN
) USING DELTA;